spring:
  application:
    name: notificacao-insumos
  kafka:
    bootstrap-servers: kafka:9092
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
server:
  servlet:
    context-path: /
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka
  instance:
    hostname: notificacao-insumos

servico:
  unidades: http://localhost:8086
  estoque: http://localhost:8085
  usuarios: http://localhost:8082
  inteligencia: http://localhost:8082
  insumos: http://localhost:8080