spring:
  application:
    name: avaliacoes
  kafka:
    bootstrap-servers: localhost:9092
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
server:
  servlet:
    context-path: /
  port: 8087
servico:
  unidades: http://localhost:8086
  estoque: http://localhost:8085
  usuarios: http://localhost:8082
  inteligencia: http://localhost:8082
  insumos: http://localhost:8080