spring:
  application:
    name: notificacao-insumos
  kafka:
    bootstrap-servers: localhost:9092
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
server:
  servlet:
    context-path: /notificacao
  port: 8086

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost

servico:
  unidades: http://localhost:8098
  inteligencia: http://localhost:8084

app:
  email:
    remetente: posfiapteam35@gmail.com
    senha: jbvp ugel gull ksqr