spring:
  application:
    name: notificacao-insumos
  kafka:
    bootstrap-servers: kafka:9092
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
server:
  servlet:
    context-path: /notificacao
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka
  instance:
    hostname: notificacao-insumos